name: Frigate
version: 0.15.0
breaking_versions:
  - 0.14.0
  - 0.14.1
  - 0.15.0
panel_icon: "mdi:cctv"
panel_title: Frigate
slug: frigate-rknpu
description: NVR with realtime local object detection for IP cameras
url: "https://github.com/blakeblackshear/frigate"
image: ghcr.io/blakeblackshear/frigate:0.15.0-rk
startup: application
boot: manual
init: false
webui: "http://[HOST]:[PORT:5000]/"
watchdog: "http://[HOST]:[PORT:5000]/"
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
homeassistant_api: true
hassio_api: true
ports:
  8555/tcp: 8555
  8555/udp: 8555
  8554/tcp: null
  8971/tcp: null
  5000/tcp: null
  1984/tcp: null
  1935/tcp: null
ports_description:
  8555/tcp: WebRTC over tcp
  8555/udp: WebRTC over udp
  8554/tcp: RTSP Restream
  8971/tcp: Authenticated Web interface
  5000/tcp: Unauthenticated Web interface (Not required for Hass.io Ingress)
  1984/tcp: go2rtc API
host_network: false
security_opt:
  - apparmor=unconfined
  - systempaths=unconfined
devices:
  - /dev/dri
  - /dev/dma_heap
  - /dev/rga
  - /dev/mpp_service
  - /dev/dri/renderD128
  - /dev/apex_0
  - /dev/apex_1
  - /dev/apex_2
  - /dev/apex_3
  - /dev/dri/card0
  - /dev/vchiq
  - /dev/video10
  - /dev/video0
usb: true
video: true
tmpfs: true
host_ipc: true
apparmor: true
full_access: true
privileged:
  - BPF
  - DAC_READ_SEARCH
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
  - PERFMON
  - SYS_ADMIN
  - SYS_MODULE
  - SYS_NICE
  - SYS_PTRACE
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_TIME
environment:
  CONFIG_FILE: /config/frigate.yml
schema:
  plus_api_key: password?
services:
  - "mqtt:want"
arch:
  - aarch64
map:
  - "media:rw"
  - "config:rw"
